"""baseline current schema

Revision ID: 3433821457fb
Revises: 
Create Date: 2026-06-10 13:09:57.537068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3433821457fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_key', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('structured_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key', 'doc_type', name='uq_documents_job_type')
    )
    op.create_table('field_help',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'column_name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_key', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary', sa.String(), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('posted_at', sa.String(), nullable=True),
    sa.Column('scraped_at', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('desirability_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_justification', sa.Text(), nullable=True),
    sa.Column('ext_seniority', sa.String(), nullable=True),
    sa.Column('ext_role_type', sa.String(), nullable=True),
    sa.Column('ext_domain', sa.String(), nullable=True),
    sa.Column('ext_work_arrangement', sa.String(), nullable=True),
    sa.Column('ext_employment_type', sa.String(), nullable=True),
    sa.Column('ext_required_skills', sa.Text(), nullable=True),
    sa.Column('ext_preferred_skills', sa.Text(), nullable=True),
    sa.Column('ext_tech_stack', sa.Text(), nullable=True),
    sa.Column('ext_key_responsibilities', sa.Text(), nullable=True),
    sa.Column('ext_company_signals', sa.Text(), nullable=True),
    sa.Column('ext_salary_min', sa.Float(), nullable=True),
    sa.Column('ext_salary_max', sa.Float(), nullable=True),
    sa.Column('resume_path', sa.String(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.Column('resume_generated_at', sa.String(), nullable=True),
    sa.Column('resume_docx_path', sa.String(), nullable=True),
    sa.Column('cover_generated_at', sa.String(), nullable=True),
    sa.Column('ats_passed', sa.Boolean(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('ats_report_json', sa.Text(), nullable=True),
    sa.Column('ats_checked_at', sa.String(), nullable=True),
    sa.Column('applied_at', sa.String(), nullable=True),
    sa.Column('sheets_row_id', sa.String(), nullable=True),
    sa.Column('unread_indicator', sa.String(), nullable=True),
    sa.Column('last_result_error', sa.Text(), nullable=True),
    sa.Column('pending_review_actions', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('resume_eval_score', sa.Float(), nullable=True),
    sa.Column('resume_eval_turns', sa.Integer(), nullable=True),
    sa.Column('resume_eval_log', sa.Text(), nullable=True),
    sa.Column('cover_eval_score', sa.Float(), nullable=True),
    sa.Column('cover_eval_turns', sa.Integer(), nullable=True),
    sa.Column('cover_eval_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_key'),
    sa.UniqueConstraint('url')
    )
    op.create_table('prompt_defaults',
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('type_key')
    )
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('type_key', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'type_key', name='uq_prompts_profile_type')
    )
    op.create_table('skill_aliases',
    sa.Column('alias_key', sa.String(), nullable=False),
    sa.Column('canonical', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('alias_key')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('skill_aliases')
    op.drop_table('prompts')
    op.drop_table('prompt_defaults')
    op.drop_table('jobs')
    op.drop_table('field_help')
    op.drop_table('documents')
    op.drop_table('config')
    # ### end Alembic commands ###
