"""add ext_skill_match to jobs

Revision ID: 866e48bc6219
Revises: aa07themes01
Create Date: 2026-06-30 22:09:01.799534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866e48bc6219'
down_revision: Union[str, Sequence[str], None] = 'aa07themes01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ext_skill_match', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ext_skill_match')
    # ### end Alembic commands ###
