// react-joyride step configs for the guided tour.
//
// Two custom fields (ignored by joyride, read by TourController):
//   openEvent  — dispatched on STEP_BEFORE to open a panel the step needs.
//   advanceOn  — the window event that advances THIS step. A step with an
//                advanceOn is "gated": it hides the footer (no Next button)
//                and waits for the user to perform the action that fires that
//                event (open the profile, expand a section, open/close the
//                prompt, close the profile). spotlightClicks lets the user
//                click the highlighted control through the overlay.

export const TOUR_STEPS = [
  // 1 — Click your name to open the profile editor.
  {
    target: '[data-tour="user-name"]',
    content: 'Click your name to open your User Profile.',
    placement: 'bottom',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    advanceOn: 'auto-apply:profile-editor-opened',
  },
  // 2 — What the profile is.
  {
    target: '[data-tour="profile-tree"]',
    content:
      "This is your User Profile — it's what we use to generate your custom résumés and cover letters.",
    placement: 'bottom-start',
    disableScrolling: true,
    disableBeacon: true,
  },
  // 3 — Sections; click one to open it.
  {
    target: '[data-tour="profile-section"]',
    content:
      "Your profile is made of sections. Double-click a section's name to rename it, or single-click a section to open it.",
    placement: 'right',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    advanceOn: 'auto-apply:section-expanded',
  },
  // 4 — Lock icon (clickable to try it; Next advances).
  {
    target: '[data-tour="section-lock"]',
    content:
      'The lock sets whether the AI may rewrite this section. Locked keeps it exactly as you typed it; unlocked lets the AI tailor it to each job. Give it a click to try — then hit Next.',
    placement: 'left',
    spotlightClicks: true,
    disableBeacon: true,
  },
  // 5 — Visibility (eye) icon (clickable to try it; Next advances).
  {
    target: '[data-tour="section-visible"]',
    content:
      'The eye controls whether this section appears in the generated document. Hide anything you want kept off the résumé. Try it — then hit Next.',
    placement: 'left',
    spotlightClicks: true,
    disableBeacon: true,
  },
  // 6 — Prompt icon; click to open the prompt editor.
  {
    target: '[data-tour="section-prompt"]',
    content:
      "This opens the section's prompt, where you steer how the AI writes it. Go ahead and click it to open.",
    placement: 'left',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    advanceOn: 'auto-apply:prompt-editor-opened',
  },
  // 7 — Prompt editor + chips; close it to return.
  {
    target: '[data-tour="prompt-modal"]',
    content:
      'This is the section prompt. Each unlocked section is generated by its own AI call, guided by what you write here. Type to try it, and drag a chip into the text to insert live context from the job or your profile. Close it with the circled ✕ to continue.',
    placement: 'top',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    ringTarget: 'prompt-close',
    advanceOn: 'auto-apply:prompt-editor-closed',
  },
  // 8 — Adding fields.
  {
    target: '[data-tour="add-field"]',
    content:
      'You can add your own fields or entries to a section here to capture anything the parser missed.',
    placement: 'top',
    disableBeacon: true,
  },
  // 9 — Close the profile to continue (spotlight the × so it stays clickable).
  {
    target: '[data-tour="profile-close"]',
    content:
      "That's the profile editor. Close it here when you're ready to continue the tour.",
    placement: 'bottom',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    advanceOn: 'auto-apply:profile-editor-closed',
  },
  // 9 — Job inbox.
  {
    target: '[data-tour="job-inbox"]',
    content:
      'This is your job inbox — every new job you add lands here, ready to work.',
    placement: 'right-start',
    disableBeacon: true,
  },
  // 10 — Manual upload.
  {
    target: '[data-tour="add-job"]',
    content: 'You can also add a job yourself by pasting a posting here.',
    placement: 'bottom',
    disableBeacon: true,
  },
  // 11 — Open the demo job (gated on the user clicking it).
  {
    target: '[data-tour="job-card"]',
    content: 'We’ve added a demo job to explore. Click it to open it.',
    placement: 'right',
    spotlightClicks: true,
    hideFooter: true,
    disableBeacon: true,
    advanceOn: 'auto-apply:job-opened',
  },
  // 12 — Score.
  {
    target: '[data-tour="job-score"]',
    content:
      'Every job is scored for fit against your profile, so you can focus on the ones worth pursuing. This one’s already scored.',
    placement: 'bottom',
    disableBeacon: true,
  },
  // 13 — Generate (switch to the résumé tab first so the button is visible).
  {
    target: '[data-tour="generate"]',
    content:
      'When you’re ready, Generate builds a tailored résumé and cover letter for this job — then you can review and refine them.',
    placement: 'left',
    disableBeacon: true,
    openEvent: 'auto-apply:show-resume-tab',
  },
  // 14 — Credits.
  {
    target: '[data-tour="credit-balance"]',
    content:
      'Scoring and generating cost credits. Here’s your balance, and where to buy more when you run low. That’s the tour!',
    placement: 'bottom',
    disableBeacon: true,
  },
]
